### ISSUE TITLE
Can't move character after quitting and playing again

### ISSUE THREAD

**Issue by mpitropov** [b24nguyen/TwinStix446#7]
To Reproduce:
-Start playing game
-Click Pause button
-Click Quit button
-Now that you are in MainMenu you should click play
-You can no longer move your character

After some investigation I have found that FixedUpdate() is not called when you enter the game for the 2nd time.

**Comment by eslong** [comment]
Fixed. See comment on PauseMenu branch.

**Comment by mpitropov** [comment]
Fixed in #6
